bugsnag/bugsnag-dsym-upload

- bin/bugsnag-dsym-upload
Fixes an issue with dSYM files failing to upload if the path contains spaces
> Handle spaces in dSYM path

- bin/bugsnag-dsym-upload
Fixes an issue where the curl command fails if the file path has commas in it (as curl uses the comma to split the file paths).
> Handle commas in the file path

- tools/fastlane-plugin/fastlane-plugin-bugsnag.gemspec
- tools/fastlane-plugin/lib/fastlane/plugin/bugsnag/actions/bugsnag_notify_build.rb
- tools/fastlane-plugin/lib/fastlane/plugin/bugsnag/actions/send_build_to_bugsnag.rb
This adds a notify action for both Android and iOS to the Fastlane plugin, allowing automatic notification of a new build.
- Retrieves API KEY, APP VERSION, and RELEASE STAGE from AppManifest.xml automatically in android
- Retrieves API KEY from info.plist automatically in iOS
- Allows configuration of all parameters through Fastlane action API
> Added notify action to Fastlane plugin

- bin/bugsnag-dsym-upload
As we're not checking that `project_root` is a directory we only need to check that it isn't zero before delivering it.
> Fixed project root to allow non-directories to be sent

- tools/fastlane-plugin/lib/fastlane/plugin/bugsnag/actions/send_build_to_bugsnag.rb
- tools/fastlane-plugin/spec/bugsnag_upload_dsym_action_spec.rb
- tools/fastlane-plugin/spec/fixtures/ios_proj/FirstRealFolder/Info.plist
- tools/fastlane-plugin/spec/fixtures/ios_proj/Project/Info.plist
- tools/fastlane-plugin/spec/fixtures/ios_proj/aaTests/Info.plist
- tools/fastlane-plugin/spec/send_build_to_bugsnag_spec.rb
- tools/fastlane-plugin/spec/spec_helper.rb
* Improves default Info.plist file detection by excluding files in `test` directories
* Changes the way that configuration options are loaded when the `config_file` option is overridden:
* If `config_file` is changed from the default, it has precedence when loading API key and version info. The file being used is printed when `send_build_to_bugsnag` is run.
* If `config_file` is nil/equal to a default value, API key and version info is loaded from params (which includes default values)
Fixes #11
> Improve default config file resolution

- bin/bugsnag-dsym-upload
- tools/fastlane-plugin/lib/fastlane/plugin/bugsnag/actions/upload_symbols_to_bugsnag.rb
- tools/fastlane-plugin/spec/bugsnag_upload_dsym_action_spec.rb
Our dSYM.zip files were uploading and it appeared to be fine, however two things seemed odd: A, our bugs weren't getting symbolified, and B, it would upload a 300gb file in a few seconds.
After digging, the problem was A, the folder structure was incorrect in the zip file we were uploading, and B, the error message returned because of this was getting swallowed up by `--silent`.
This PR is my remedy to B, which when turned on identified the original problem...
```
Uploading files to https://upload.bugsnag.com
Preparing to upload /var/folders/j7/x2d8y8x16rg4mfrt1dh6scqr0000gq/T/bugsnag-dsym-upload.UCI3PQZe/*.dSYM
Skipping file missing DWARF data: /var/folders/j7/x2d8y8x16rg4mfrt1dh6scqr0000gq/T/bugsnag-dsym-upload.UCI3PQZe/*.dSYM
1 files failed to upload
```
At the very least, I think a …
> Halt Action when bash script is borked

- CHANGELOG.md
- CONTRIBUTING.md
- Makefile
- features/fixtures/fl-project/Gemfile
- features/support/env.rb
- tools/fastlane-plugin/LICENSE.txt
- tools/fastlane-plugin/Rakefile
- tools/fastlane-plugin/bugsnag-dsym-upload
- tools/fastlane-plugin/spec/bugsnag_upload_dsym_action_spec.rb
At some point, linked gem files started being copied directly instead of
becoming actual files in gems. This fixes the packaging and process for
generating the gem to ensure that the resulting binary can run.
* New `build` and `release` commands in the Rakefile to ensure that included files are up to date
* New release instructions in CONTRIBUTING.md
* Tested by building and installing the gem locally with RubyGems 2.7.7
* Updated integration tests to use a prebuilt artifact and catch these kinds of issues in CI
Fixes #21
For the submitter, initial self-review:
- This pull request is ready for:
For the pull request reviewer(s), this changeset has been reviewed for:
> fix: Convert linked gem files to copies

- features/fastlane_dsym_upload.feature
- tools/fastlane-plugin/lib/fastlane/plugin/bugsnag/actions/upload_symbols_to_bugsnag.rb
- Fixes broken Maze-runner scenario
- Fixes typo in invalid APIKey message
> Fix: Invalid test and invalid APIKey message

- CHANGELOG.md
- Gemfile
- bin/bugsnag-dsym-upload
- features/dsym_upload.feature
- features/fastlane_dsym_upload.feature
This should address this issue: https://github.com/bugsnag/bugsnag-dsym-upload/issues/33
> Pin the HTTP version used by dSYM upload to 1.1

- CHANGELOG.md
- bin/bugsnag-dsym-upload
Fixes #38.
Tested with the following,
```bash
bin/bugsnag-dsym-upload --upload-server https://httpstat.us/503 dsym_archive_test.zip && echo success
Uploading UUID: 04E51379-A668-3ECA-975C-50EE0D2921CA (armv7) /var/folders/0y/bts_0rzj5q91dn9y1wdjgcjh0000gn/T/bugsnag-dsym-upload.XXX.mPkY7YEL/04E51379-A668-3ECA-975C-50EE0D2921CA.dSYM/Contents/Resources/DWARF/libswiftCoreImage.dylib
curl: (22) The requested URL returned error: 503 Service Unavailable
Uploading UUID: 1066EDB0-4E4E-393D-845B-50BFDE11191A (arm64) /var/folders/0y/bts_0rzj5q91dn9y1wdjgcjh0000gn/T/bugsnag-dsym-upload.XXX.mPkY7YEL/1066EDB0-4E4E-393D-845B-50BFDE11191A.dSYM/Contents/Resources/DWARF/libswiftCoreImage.dylib
curl: (22) The requested URL returned error: 503 Service Unavailable
Uploading UUID: …
```
> Set a non zero exit code on upload errors

- tools/fastlane-plugin/fastlane-plugin-bugsnag.gemspec
The latest parallel gem ([1.20.0](https://rubygems.org/gems/parallel/versions/1.20.0)) has dropped support for Ruby 2.4. Added a restriction on the dependency, which is included through rubocop (~> 1.10).
Re-running CI
> ci: restrict parallel gem version to support ruby 2.4.x

- .travis.yml
Bump to OS (and Xcode) versions to get the build working again.
> Bump build OS versions

- .buildkite/pipeline.yml
- Gemfile
- config/.gitignore
- docker-compose.yml
- dockerfiles/Dockerfile.audit
- scripts/license_finder.sh
Add license checking to the CI pipeline.  The existing pipeline is based in Travis, so I've set up the necessary webhook in Buildkite for this in order that we can take a consistent approach.
> License auditing

- .github/workflows/test.yml
- Makefile
- tools/fastlane-plugin/Rakefile
Running rspec via Rake is responsible for false positives on CI — `system` doesn't raise when the command fails, it returns `false` instead (unless the `exception` keyword argument is given)
Running rspec directly removes this layer of indirection and isn't any more complicated as we're not passing any options in the Rakefile anyway
This means the Ubuntu build is now failing as expected
> Fix false positives on CI

- tools/fastlane-plugin/lib/fastlane/plugin/bugsnag/actions/send_build_to_bugsnag.rb
- tools/fastlane-plugin/lib/fastlane/plugin/bugsnag/actions/upload_symbols_to_bugsnag.rb
This makes the plist that gets picked deterministic, e.g. different operating systems can return files in different orders
This is the reason for the tests failing on Ubuntu but passing on macOS
> Sort the possible plist paths before picking one

- tools/fastlane-plugin/lib/fastlane/plugin/bugsnag/actions/upload_symbols_to_bugsnag.rb
`download_dsyms` and `gym` dSYM output locations were incorrectly switched.
* `gym` produces `SharedValues::DSYM_OUTPUT_PATH`
* `download_dsyms` produces `SharedValues::DSYM_PATHS`
This PR fixes this switch. 
There should be no change functionality, as previously we would just refer to `download_dsyms` location as that generated by `gym` and vice-versa, but the dSYMs would still be uploaded as expected.
> fix(fl-sym-upload): correct variable names for actions

- CHANGELOG.md
- tools/fastlane-plugin/lib/fastlane/plugin/bugsnag/actions/send_build_to_bugsnag.rb
- tools/fastlane-plugin/spec/send_build_to_bugsnag_spec.rb
This update makes it possible to report metadata as part of the Fastlane `send_build_to_bugsnag` function. In Fastlane it was not previously possible to do this, where it was with other build reporting methods. 
The changes made add a new config item, and add the provided metadata to the payload.
Addition of new config item and metadata payload. Bumped version number. 
Tested in my local development environment using custom endpoints. When provided, metadata will be added to the reported release.
> Allow metadata in Fastlane send_build_to_bugsnag reports

- tools/fastlane-plugin/lib/fastlane/plugin/bugsnag/actions/find_info_plist_path.rb
- tools/fastlane-plugin/lib/fastlane/plugin/bugsnag/actions/send_build_to_bugsnag.rb
- tools/fastlane-plugin/lib/fastlane/plugin/bugsnag/actions/upload_symbols_to_bugsnag.rb
Internal note (will be removed before release): https://smartbear.atlassian.net/browse/PLAT-4743 
Aims to put `default_info_plist_path` method into shared class to reduce copy pasted code. 
I decided that the existing method should be moved to a new class file. Currently the new class file will be located in the same directory as `send_build_to_bugsnag.rb` and `upload_symbols_to_bugsnag.rb`
New file `find_info_plist_path.rb` added to contain `FindInfoPlist` class. Old copy pasted `default_info_plist_path` methods removed from `end_build...` and `upload_dsym...` files. 
Unit and e2e tests run locally. All pass fine. Possibly worth adding new unit test for new class.
> Moving default_info_plist_path to shared class

- .buildkite/pipeline.yml
- features/fastlane_build_report.feature
- features/fixtures/fl-project/fastlane/Fastfile
- features/steps/fastlane_build_report_steps.rb
- features/support/env.rb
- tools/fastlane-plugin/lib/fastlane/plugin/bugsnag/actions/send_build_to_bugsnag.rb
There are currently no or few e2e tests for Fastlanes `send_build_to_bugsnag` function. This PR intends to rectify that making it easier to test future changes to the tool.
Cucumber was used for e2e tests, with most changes being inspired by similar e2e tests for Fastlane dsym upload functions.
`fastlane_build_report.feature` file added to house all build reporting scenarios. Modifications made to other files to enable test functionality. 
Step added to the Buildkite pipeline to run the e2e tests.
> Starting to add e2e tests for fastlane build reporter

- .github/workflows/test.yml
Tests likely started failing as Github bumped their support for macOS versions. 
This PR bumps the macOS version used for GitHub tests. from `10.15` to `11`
> Bumping macOS version for GitHub tests
